language: node_js
node_js:
  - '7.5.0'
before_install:
  - npm install -g grunt-cli bower
  - bower install
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'reactive-coffee' ]; then cd .. && eval "mv $currentfolder reactive-coffee" && cd reactive-coffee; fi
install: npm install
