// Generated by CoffeeScript 1.6.3
(function() {
  define(['domReady!', 'jquery', 'reactive-coffee', 'views/todoApp'], function(document, $, rx, todoApp) {
    var tasks;
    tasks = rx.array();
    window.tasks = tasks;
    return $('body').prepend(todoApp(tasks));
  });

}).call(this);
